### ISSUE TITLE
why two onChanged events?

### ISSUE THREAD

**Issue by mu578** [kevin--/bindey#8]
```
auto onChanged( typename decltype( changed )::slot_type&& c, bool now = false )
{
   auto connection = changed.connect( std::move( c ) );
   if ( now )
   {
      changed( mStorage );
   }
   return connection;
}
```
edit : _you like very much extra spaces_

**Comment by kevin--** [comment]
Imo separate methods are more readable than default arguments. In general the expectation is that `onChangedAndNow` is only used when the property binding is first established for the use case around synchronizing some state to a property during construction (a View for example that who's lifetime is shorter than the property)

**Comment by mu578** [comment]
ok, then name it something like `apply` as it is not really an `event`  but an atomic op.

```
auto apply( typename decltype( changed )::slot_type&& c)
{
   auto connection = changed.connect( std::move( c ) );
   changed( mStorage );
   return connection;
}
```
